feat: fastify eject
fastify/fastify-cli pull request #302
Opened 2020-12-19 11:53 UTC by joobisb

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

This PR adds support for ESM modules as discussed in #277

2020-12-19 12:07 UTC, mcollina requested changes

2020-12-19 12:07 UTC, mcollina commented on templates/eject/server.js
> +  pluginTimeout: 10000
This is the default, we can remove

2020-12-19 12:07 UTC, mcollina commented on help/eject.txt
> +Turns your application into a standalone executable with a server.js file being added.
Can you document the PORT env variable?

2020-12-19 12:09 UTC, zekth commented on templates/eject/server.js
> +app.register(require('./app.js'))
i'd personally have a proper statement:
`const app_service = require('./app.js')`

2020-12-19 12:15 UTC, joobisb commented on help/eject.txt
> +Turns your application into a standalone executable with a server.js file being added.
sure

2020-12-19 12:15 UTC, joobisb commented on templates/eject/server.js
> +app.register(require('./app.js'))
okay. i'll update

2020-12-19 12:33 UTC, joobisb commented
@mcollina @zekth i've updated the PR. please have a look

2020-12-19 13:06 UTC, zekth approved these changes
lgtm

2020-12-20 09:27 UTC, mcollina approved these changes
lgtm

2020-12-20 11:46 UTC, merged