Add .env conf to graceful termination strategy suggested by templates
fastify/fastify-cli pull request #537
Opened 2022-08-13 18:38 UTC by avanelli

### Description 
Add use of .env FASTIFY_CLOSE_GRACE_DELAY for closeWithGrace in templates eject/server.js
Related to Issue  #531

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2022-08-14 10:28 UTC, mcollina requested changes
Could you do the same in `start.js`?

Docs and tests are missing too

2022-08-14 14:33 UTC, avanelli commented
> Could you do the same in `start.js`?

Adding to `start.js` should be helpful to add it also as CLI parameter `--close-grace-delay`. Is it ok? 
I can add the new parameter tests in `args.test.js`.
If we need some specific test about `closeWithGrace` timings in `start.test.js`, I will need some indication or example.

> Docs and tests are missing too

About templates eject/server.js and eject-ts/server.ts, I didn't find any relevant tests or docs.
I only changed the server.js code in README.md to reflect the template.

2022-08-16 07:30 UTC, mcollina commented
> Adding to start.js should be helpful to add it also as CLI parameter --close-grace-delay. Is it ok?


That would be ok!

Cheers

2022-08-16 12:06 UTC, mcollina approved these changes
lgtm

2022-08-16 13:16 UTC, Fdawgs approved these changes

2022-08-16 14:02 UTC, merged