manual loading and parsing of dotenv in watch mode #558
fastify/fastify-cli pull request #559
Opened 2022-10-14 19:20 UTC by tandibar

I think this could be the fix for the issue #558 that I opened.

The problem with `dotenv.config().parsed` is that `dotenv.config()` modifies the `process.env`. So the fix uses `dotenv.parse()` directly so that `process.env is untouched.

All tests are green. I will provide an additional test in the next days.

#### Checklist

- [ ] run `npm run test` ~and `npm run benchmark`~
- [ ] tests and/or benchmarks are included
- [ ] ~documentation is changed or added~
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2022-10-14 20:00 UTC, mcollina approved these changes
lgtm

2022-10-14 20:01 UTC, mcollina commented
Thanks for opening a PR! Can you please add a unit test?

2022-10-14 20:02 UTC, mcollina requested changes
Thanks for opening a PR! Can you please add a unit test?

2022-10-15 08:55 UTC, tandibar commented
So I added a unit test and implemented the feature. The problem is, that it breaks another feature, see test `test/start.test.js should reload the env on restart when watching`. In the current implementation I think it is very hard to have both features. For me it would be more consistent if dotenv does not change its behavior in watch mode. But that would mean, that you have to restart your server if you change your `.env` even in watch mode.
What do you think?

2022-10-15 10:00 UTC, mcollina commented
> that would mean, that you have to restart your server if you change your .env even in watch mode.

Why? I _think_ it might be possible to have the env variables defined in process.env to have priority over the ones in .env.
Or viceversa. I think the surprising behavior is lack of consistency.

2022-11-11 10:59 UTC, tandibar commented
So the problem ist, that `dotenv` is already loaded before, so we cannot just check which env vars are already present, because all are present. So I decided to check if there is a difference between the `process.env` and the parsed dotenv. If yes, we should not overwrite the env var. If it is the same, it seems to be managed by dotenv file, so we should overwrite.
Tests are now all passing, so I think that is the solution.

2025-11-08 10:19 UTC, closed without merging